version: "3.9"

volumes:
  postgres_data:
  grafana-storage:
  prometheus-data:

networks:
  ion-network:

services:
  db:
    platform: linux/amd64
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=ion
      - POSTGRES_PASSWORD=ion
      - POSTGRES_DB=ion
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ion-network

  redis:
    image: redis:alpine
    restart: always
    networks:
      - ion-network

  jenkins:
    build: ./infrastructure/jenkins
    user: root
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=true
    networks:
      - ion-network

  ion-repo-service:
    build:
      context: .
      dockerfile: apps/ion-repo-service/Dockerfile
    container_name: ion-repo-service
    ports:
      - "3002:3002"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - ion-network

  ion-request-service:
    build:
      context: .
      dockerfile: apps/ion-request-service/Dockerfile
    container_name: ion-request-service
    ports:
      - "3003:3003"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - ion-network

  ion-websocket:
    build:
      context: .
      dockerfile: apps/ion-websocket/Dockerfile
    container_name: ion-websocket
    ports:
      - "8081:8081"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - ion-network

  ion-deployment-service:
    build:
      context: .
      dockerfile: apps/ion-deployment-service/Dockerfile
    container_name: ion-deployment-service
    ports:
      - "3005:3005"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - ion-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - ion-network
    depends_on:
      - ion-request-service
      - ion-repo-service
      - ion-deployment-service
      - ion-websocket

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./infrastructure/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - ion-network
    depends_on:
      - prometheus
