global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "ion-services"
    static_configs:
      - targets:
          - ion-request-service:3003
          - ion-repo-service:3002
          - ion-deployment-service:3005
          - ion-websocket:8081